# Generated by Django 5.1.6 on 2025-03-06 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_is_completed_item_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ending',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 23, 59, 59)),
        ),
    ]
